### ISSUE TITLE
Translations for Structures

### ISSUE THREAD

**Issue by LuminaHeinsborough** [celsiusqc/totw_modded_mod#10]
For the compatibalities with Nature’s Compass and Explorer's Compass.
[zh_cn.json](https://github.com/celsiusqc/totw_modded_mod/files/13928324/zh_cn.json)

**Comment by zachsai** [comment]
I'd have to write code for all the other terms since I don't use translations files for the default english version. I'll keep this open for in the future if I ever do change things
