### ISSUE TITLE
Tag Spam 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [celsiusqc/totw_modded_mod#11]
I don't have these additional mods, I understand that this is just a warning) it's just red for some reason, not orange, and it makes it a little difficult to track errors. 
Well, according to my feelings)

I only have to: 

1. totw_modded-1.0.1-1.19.2.jar
2. totw_additions-1.2.3-1.19.x-forge.jar

I didn't put on mods: 

1. twilight forest
2. blue skies
3. bumble zone tower
4. ad_astra
5. mushroom_forest

![image](https://github.com/celsiusqc/totw_modded_mod/assets/106809386/3d652971-e968-4826-8ca8-89b8174024af)

> [19Feb2024 01:35:36.361] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/tw_mangrove_tower: twilightforest:swamp (from totw_modded-1.0.1-1.19.2.jar), twilightforest:fire_swamp (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.363] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/everdawn_tower: blue_skies:unorthodox_valley (from totw_modded-1.0.1-1.19.2.jar), blue_skies:shaded_woodlands (from totw_modded-1.0.1-1.19.2.jar), blue_skies:crystal_dunes (from totw_modded-1.0.1-1.19.2.jar), blue_skies:crystal_dunes_spikes (from totw_modded-1.0.1-1.19.2.jar), blue_skies:sunset_maple_forest (from totw_modded-1.0.1-1.19.2.jar), blue_skies:rising_creek (from totw_modded-1.0.1-1.19.2.jar), blue_skies:crystal_roughs (from totw_modded-1.0.1-1.19.2.jar), blue_skies:searing_grassland (from totw_modded-1.0.1-1.19.2.jar), blue_skies:crescent_orchard (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.367] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/bumblezone_tower: the_bumblezone:crystal_canyon (from totw_modded-1.0.1-1.19.2.jar), the_bumblezone:pollinated_fields (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.367] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/venus_tower: ad_astra:infernal_venus_barrens (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.369] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/moon_tower: ad_astra:lunar_wastelands (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.371] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/tw_canopy_tower: twilightforest:forest (from totw_modded-1.0.1-1.19.2.jar), twilightforest:spooky_forest (from totw_modded-1.0.1-1.19.2.jar), twilightforest:mushroom_forest (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.371] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/everbright_tower: blue_skies:calming_skies (from totw_modded-1.0.1-1.19.2.jar), blue_skies:brightlands (from totw_modded-1.0.1-1.19.2.jar), blue_skies:slushlands (from totw_modded-1.0.1-1.19.2.jar), blue_skies:frostbitten_forest (from totw_modded-1.0.1-1.19.2.jar), blue_skies:frostbitten_forest_clearing (from totw_modded-1.0.1-1.19.2.jar), blue_skies:snow_covered_pines (from totw_modded-1.0.1-1.19.2.jar), blue_skies:brisk_meadow (from totw_modded-1.0.1-1.19.2.jar), blue_skies:polar_highland (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.371] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/mars_tower: ad_astra:martian_canyon_creek (from totw_modded-1.0.1-1.19.2.jar), ad_astra:martian_wastelands (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.372] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/glacio_tower: ad_astra:glacio_snowy_barrens (from totw_modded-1.0.1-1.19.2.jar), ad_astra:glacio_ice_peaks (from totw_modded-1.0.1-1.19.2.jar)
> [19Feb2024 01:35:36.373] [Worker-ResourceReload-0/ERROR] [net.minecraft.tags.TagLoader/]: [Load My Fucking Tags] Couldn't load certain entries with the tag totw_modded:has_structure/mercury_tower: ad_astra:mercury_deltas (from totw_modded-1.0.1-1.19.2.jar)
>

**Comment by zachsai** [comment]
Yeah, that's because the tag's are being read, but not loaded since the mod's are not present. Shouldn't be anything to worry about
