### ISSUE TITLE
A tower without a roof 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [celsiusqc/totw_modded_mod#12]
Something obviously went wrong)) Did her tower get blown off?
![2024-02-19_03 23 33](https://github.com/celsiusqc/totw_modded_mod/assets/106809386/f84e5a08-b498-4888-8bfa-927603ca4295)
![2024-02-19_03 23 30](https://github.com/celsiusqc/totw_modded_mod/assets/106809386/274e47ff-a524-47da-a9d5-d669778b5f41)

**Comment by nco2k** [comment]
i have the same issue. have you figured out whats causing this?

**Comment by zachsai** [comment]
It's one of the tower variants

**Comment by nco2k** [comment]
oh okay. any chance you could give us an option to disable generating them?
