### ISSUE TITLE
fabric 1.20.1 paragliders arent included with the mod

### ISSUE THREAD

**Issue by Alpdrucken** [celsiusqc/totw_modded_mod#22]
I read on the curseforge page that paragliders were supposed to be included with the mod, but i had to download the standalone paraglider mod for it to work :)

**Comment by Yo-Snowpro** [comment]
Same for me but with 1.21 fabric

**Comment by zachsai** [comment]
You need to download the mod for said paraglider or glider mod to be loaded in the loot table of my mod
