### ISSUE TITLE
Custom waystone names aren't applied

### ISSUE THREAD

**Issue by Kelpiesaurus** [celsiusqc/totw_modded_mod#3]
Hello,

I have 200 custom names in the Waystones config, and they generate fine with regular waystones in villages & elsewhere, but waystones at the top of towers do not get assigned a name from the list. When I right-click on them, the runes light up but the label continues to say "Undiscovered." I have attached before & after pics below.

![TowersWildWaystoneUndiscovered](https://github.com/celsiusqc/totw_modded_mod/assets/126528970/440a5f54-96a3-4655-ba33-cdc7ab81b1ea)
![TowersWildWaystoneDiscovered](https://github.com/celsiusqc/totw_modded_mod/assets/126528970/e8aca4f0-7e1e-4267-9833-6f9872d0a69b)

Also, they show up as "unnamed" in the GUI:
![TowersWildWaystoneUnnamed](https://github.com/celsiusqc/totw_modded_mod/assets/126528970/3271e1cf-a005-4ebb-b079-69884d41df17)

**Comment by zachsai** [comment]
Hi,
Could you test to see if this happens with all variants?

If so, it would be the way I made the waystones generate with the structure. They require players to rename them in that case.

Also, please let me know which version of the mod you are using and which version of minecraft

**Comment by zachsai** [comment]
It seems to be occurring on other variants. I will have to run some tests on my end to try and fix, but frankly it is not a top priority of mine since waystones can easily be renamed by players.

**Comment by ZEROX7** [comment]
the issue also happens if none custom names are provided, in my case the player are not allowed to rename them, wich kinda sucks for them.
EDIT: it also prevents JMI to work correctly no marked is placed

**Comment by zachsai** [comment]
I am currently working on trying to get this fixed

**Comment by SigmaFlame** [comment]
They really need be generated with random names.
Or at least the dimension name and coordinate should be fine as well.

Your mod would be perfect but it is sadly incompatible with the fact we want waystones being unable to be moved by players.

**Comment by zachsai** [comment]
The waystones not being breakable should work. I have it working for my own modpack with my own mod. Please test about your configs. My modpack Create Planetary has it working.
For the random names, I tried fixing it over the summer but ran into difficulties. I tried getting help from the Waystones mod author, but his advice did not work. Feel free to test it out, contact them, make a pull request and we can try and get it fixed.

**Comment by SigmaFlame** [comment]
Waystones generated by Waystones itself are unbreakable. (the ones in villages and in the wild)
But ... Waystones generated by your mod (in the top of a tower) are still breakable.
Your mod ignore the setting of "generatedWaystonesUnbreakable"

There is another way to make them all unbreakable and that's work with your mod, the setting "restrictToCreative"
But, this setting prevent waystones to be renamed by players and as your waystones does not have a name, it's very problematic

**Comment by zachsai** [comment]
Are you sure? I believe I had this working in 1.20.1 version with the waystones being unbreakable and you being able to rename them. I'll try and test this out in the next few days and find a fix if so

**Comment by AikaBack** [comment]
this issue with unnamed towers is still on 1.20.1 mod version totw_modded-1.0.2-1.20.1

**Comment by AikaBack** [comment]
aand its still breakable with unbreakable config

**Comment by zachsai** [comment]
Unnamed issue is still on-going, I am attempting to get help from the Waystones mod creator, as the issue seems to be coming from their end. New version will be releasing, but it only adds a Aether tower, and does not fix the issue.

Also, I checked, configs for only allowing creative players to break towers / unbreakable if naturally generated, the configs work as intended

**Comment by zachsai** [comment]
Found the fix for the waystones generating names on world gen and making the unbreakable config be respected. I will be updating all structure files and updating the versions accordingly. Fixes should be up soon
