### ISSUE TITLE
totw_modded-1.0.1-1.19.2 tries to load blocks from mods that I don't have installed causing game to hang/lag/

### ISSUE THREAD

**Issue by Minebrah** [celsiusqc/totw_modded_mod#4]
https://gist.github.com/Minebrah/39d3aac624e10036e5c3105ae845eae5

**Comment by zachsai** [comment]
which dimension were you in / which biome? It tries to load a block from Blue Skies mod, although those should only spawn in the blue skies dimensions

**Comment by zachsai** [comment]
Closing this issue as no response was provided
