### ISSUE TITLE
Config options 1.20.1 Forge

### ISSUE THREAD

**Issue by NateKDavis** [celsiusqc/totw_modded_mod#5]
In 1.20.1 forge 47.2.0 there does not seem to be any config options. 
I have the config in waystone for only allowing creative players to interact with Waystones that are generated but Towers of the wild does not seem to be effect by that.

**Comment by zachsai** [comment]
I do not have configs created for the mod unfortunately, and do not know how I would create any.

**Comment by SigmaFlame** [comment]
But can you read the waystone config and make yours generated correctly please?

**Comment by zachsai** [comment]
Is this issue still on-going? I was not encountering this issue in my testing
