### ISSUE TITLE
Incompatible with Rats 8.1

### ISSUE THREAD

**Issue by gardenappl** [celsiusqc/totw_modded_mod#6]
I'm not sure whether the mod is *genuinely* incompatible with Rats 8.1 or if it's just a dependency issue. But right now the game straight up refuses to load due to declared dependency version.

> [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Unsupported installed optional dependencies:
        Mod ID: 'rats', Requested by: 'totw_modded', Expected range: '[8.0.6,)', Actual version: '1.20.1-8.1'

**Comment by moninformateur** [comment]
Can confirm I have the same issue on my end:

When launching the game with the new Rats [1.20-8.1](https://legacy.curseforge.com/minecraft/mc-mods/rats/files/4785586), I get a crash.

[Here's the link to the mclo.gs log](https://mclo.gs/tiKm0ke)

Log error is ... 
```
Error during pre-loading phas
net.minecraftforge.fml.ModLoadingException: Mod totw_modded only supports rats 8.0.6 or above
Currently, rats is 1.20.1-8.1
```

**Comment by DaddySpin** [comment]
I can also confirm rats 8.1 and 8.1.1 are incompatible with TOTW: Modded.

**Comment by Wolris** [comment]
I get a similar message 

[main/ERROR]: Unsupported installed optional dependencies:
Mod ID: 'rats', Requested by: 'totw_modded', Expected range: '[8.0.6,)', Actual version: '1.20.1-8.1.1'

Looking forward to updating, but intil this is fixed I'll be in version 8.0.6.  Thanks, Devs!

**Comment by zachsai** [comment]
I will try and test to fix.

**Comment by zachsai** [comment]
The fix should be out now! :)

**Comment by zachsai** [comment]
New patch is out with the fix to be used with the newer Rats version
