### ISSUE TITLE
Game will not load with the rats mod installed as it says it only supports 8.06 or above but installed version is 8.1.2

### ISSUE THREAD

**Issue by MarioHunter07** [celsiusqc/totw_modded_mod#7]
![image](https://github.com/celsiusqc/totw_modded_mod/assets/52632692/1ee47d55-20a3-407d-addf-1a12ccd92d53)

**Comment by zachsai** [comment]
Which version of the mod are you using? The latest TOTW_Modded should have fixed it

**Comment by Aoriseth** [comment]
I'm having the same issue with Towers of the wild modded (version 1.0.1)

I downloaded the newest version of Towers of the wild from curseforge and that fixed it.

But the newest version (1.0.2) is not available on modrinth. And my mod launcher (prism) cannot download Towers of the wild from curseforge for some reason.

**Comment by zachsai** [comment]
Modrinth version just got uploaded, idk how long it takes to get approved, but should appear soon @Aoriseth
