### ISSUE TITLE
[net.minecraft.tags.TagLoader/]: Couldn't load tag totw_modded:has_structure/ratlantis_tower as it is missing following references: rats:ratlantis (from totw_modded-1.0.2-1.20.1.jar)

### ISSUE THREAD

**Issue by MrLoLf** [celsiusqc/totw_modded_mod#8]
I found this line `[net.minecraft.tags.TagLoader/]: Couldn't load tag totw_modded:has_structure/ratlantis_tower as it is missing following references: rats:ratlantis (from totw_modded-1.0.2-1.20.1.jar)` in my 
[debug.log](https://github.com/celsiusqc/totw_modded_mod/files/13636359/debug.log)
I use version 1.0.2-1.20.1 of your mod on atm9 modpack version 0.2.28 it uses forger version 47.2.16

**Comment by zachsai** [comment]
This happens if the rats mod is not installed. Should not cause any issues though
