### ISSUE TITLE
[1.20.1] This mod ignore the generatedWaystonesUnbreakable settings

### ISSUE THREAD

**Issue by SigmaFlame** [celsiusqc/totw_modded_mod#9]
Hello,

In the config of the waystone mod, there is a setting to make all generated waystones unbreakable.
But the waystones generated by your mod are still breakable regardless.

Also I didn't find any settings for your mod.

**Comment by zachsai** [comment]
I just tested in a fresh instance, and the waystones are non breakable when i have these settings for waystones:

[restrictions]
	#If enabled, only creative players can place, edit or break waystones. This does NOT disable the crafting recipe.
	restrictToCreative = true
	#If enabled, only the owner of a waystone (the one who placed it) can rename it.
	restrictRenameToOwner = false
	#If enabled, waystones generated in worldgen are unbreakable.
	generatedWaystonesUnbreakable = true

**Comment by Hakuyako** [comment]
> I just tested in a fresh instance, and the waystones are non breakable when i have these settings for waystones:
> 
> [restrictions] #If enabled, only creative players can place, edit or break waystones. This does NOT disable the crafting recipe. restrictToCreative = true #If enabled, only the owner of a waystone (the one who placed it) can rename it. restrictRenameToOwner = false #If enabled, waystones generated in worldgen are unbreakable. generatedWaystonesUnbreakable = true

I have same issue, actually this issue has existed for a long time.
I set "generatedWaystonesUnbreakable" to true for waystones, he waystones generated by totw are still destructible in survival mode. 

I tested this problem in fresh instance for several times.

**My game version :**
1.20.1-FORGE
totw_modded-1.0.3-1.20.1
waystones-forge-1.20-14.1.3.jar

**My setting for waystones**

> [restrictions]
> 	#If enabled, only creative players can place, edit or break waystones. This does NOT disable the crafting recipe.
> 	restrictToCreative = false
> 	#If enabled, only the owner of a waystone (the one who placed it) can rename it.
> 	restrictRenameToOwner = true
> 	#If enabled, waystones generated in worldgen are unbreakable.
> 	generatedWaystonesUnbreakable = true


If you set restrictToCreative to false, which means that no matter whether the waystones are generated by the map or placed with hand, it cannot be broke in survival mode.

**Comment by zachsai** [comment]
This seems to be a bug with Waystones mod. I have been in contact with the dev. It is also the reason for the bug regarding the name of the waystone being stuck at <unnamed>

**Comment by zachsai** [comment]
Found the solution, will come in patch 1.0.4
